[meta title:"Bagehot" description:" Lombard Street : A Description of the Money Market " /]

[Header
  title: "Lombard Street"
  subtitle:" A Description of the Money Market by Walter Bagehot"
  author:"John Rieth"
  authorLink:"https://idyll-lang.github.io" /]



### Introduction by Frank C. Genovese
Central banking, the art of the banker’s bank, has grown out of a troubled past.  Its stages of evolution are marked by three great docu­ments, Lombard  Street, the  Macmillan  Report,  and  the  Radcliffe Report. Each of these arose out of the accumulated concern with the progress of events in the world.  Each represented a search for answers  to urgent questions  of its  day

The reports deal largely with the adjustments and modifications of British central banking to external difficulties and problems. The Macmillan Report appeared as the world crumbled into the depres­ sion of the 1930’s. TTie Radcliffe Report of 1959 appeared in an epoch of shaky alliances ai.d emerging trading blocs. Both followed a period of inflation and international readjustment after the holocaust of war. It was in the aftermath of war also that emerging capitalism and deposit banking fell into the difficulties which led to the production of the greatest of the documents, Lombard Street. Priority in time gave it the task, not of suggesting necessary modifications in central banking, but the more vital one, of enumerating the prime func­ tions of a central bank. It created the concept of a central bank and thereby has for all time assured to its author a secure position in bank­ ing thought.

The Macmillan and Radcliffe studies are the works of many men who had staffs and the benefit of much data. Lombard Street is the product of only one man, Walter Bagehot, and as such reflects his deep understanding and intimate knowledge of banking, business and fiscal affairs. Its ideas were first expressed in a series of articles in The Economist during the 1 850’s and were put into book form in 1870. During his relatively short lifetime (1826-1877) Bagehot wrote extensively on a wide range of literary, political, and economic sub­ jects. His collected works run into five substantial volumes. While obviously a many faceted man, his main interests lay in the broad field of political economy and his chief occupation was that of editor of The Economist, the world’s most influential financial paper.



